In [4]:
import cv2
# import pyrealsense as rs
import numpy as np
from camCalibration import *
from Modbus_DW import *
from camera import *
from demo import demo

ImportError: cannot import name 'aruco' from 'cv2' (/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/cv2/__init__.py)

## make calibration data

In [9]:
from pyModbusTCP.client import ModbusClient
c = ModbusClient()
servers_host = '192.168.1.1'
c.host = '192.168.1.1'
c.port = 502


In [10]:
c=connectRobot(SERVER_HOST = '192.168.1.1')

# makeCamset(c,path="picture/demo",pixel="high",p0=pos)   #p0=pos
# # teachPoint(c,pos)

NameError: name 'connectRobot' is not defined

In [11]:
path="./picture/11_29_2"
with open(path+"/data/HandEye.yaml", 'r') as f:
    data = yaml.load(f, Loader=yaml.Loader)
print(data)

NameError: name 'yaml' is not defined

## run Hand Eye calibration

In [38]:
cam1=Charuco()
cam1.Calibration(imgPath="./picture/11_29_2",show=True)
cam1.HandEyeCalibration_EyeInHand()#new 按照數字讀圖

c=connectRobot(SERVER_HOST = "192.168.1.1")
RWTool(c,path="./picture/11_29_2")

[[ 9.12082835e+02  0.00000000e+00  6.60771927e+02]
 [ 0.00000000e+00  1.97486722e+03 -4.26891197e+02]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00]]
[[ 0.77745702 -0.27871953 -0.33480723  0.00481466  0.03183092]]
error: 48.854782194203516
distortion: [[ 0.77745702 -0.27871953 -0.33480723  0.00481466  0.03183092]]
目錄存在。


AttributeError: module 'cv2.aruco' has no attribute 'drawAxis'

## demo UF

In [ ]:
pipeline=startCamera()
# run=demo("./picture/8_9")
run=demo("./picture/11_29_2")
c=connectRobot(SERVER_HOST = "192.168.1.1")

try:
    while True:
        Cam,colorImg,depthImg=CameraStream(pipeline)
        if(Cam==0):#esc
            break
        elif(Cam==1):
            continue
        elif(Cam==3):#press 1
            #print("1")
            a,UF=run.getSinglePose(colorImg)
            print("UF:",UF)
            o,x,y=run.calUF(c)
            setUF(c,o,x,y)
            #setUF(c,UF[0],UF[1],UF[2],TF=7)
#             pointBoardPose(c)
#             teachPoint(c,[437.195, -50.004, 570.37, 177.131, -1.512, -2.359])#origin
            #graspDemo(c)
        else:
#             print("123")
            continue
        
finally:

    # Stop streaming
    pipeline.stop()
    cv2.destroyAllWindows()
    #closeRobot(c)

hello
{'ARUCO_size': 6, 'dist': array([[ 0.16269981, -0.21051283,  0.00716262, -0.00676228, -0.26399864]]), 'iMtx': array([[947.35677163,   0.        , 631.87979122],
       [  0.        , 949.73990136, 367.38558855],
       [  0.        ,   0.        ,   1.        ]]), 'markerL': 0.015, 'squareL': 0.02, 'x': 9, 'y': 12}
connect success
DRA is runing now
UF: [-41.295681100358635, -7.322228942469352, 420.9679920735176, 178.96042090725442, 4.382999345510111, -86.58219522551404]
read try: 0
UF: [9.094424940419607, -5.3866536991668825, 324.15538452250405, 179.53859750790286, 0.13995112852978142, -88.94951178106668]
read try: 0


In [ ]:
# UF.shape
#changeUF(c,UF=0)  #board UF=8
# changeTF(c,TF=0) #camera tool frame = 7,筷子=8


In [2]:
# def pointBoardPose(c):
# #     changeUF(c,UF=8)  #board UF=8
# #     changeTF(c,TF=7)
# #     teachPoint(c,[437.195, -50.004, 570.37, 177.131, -1.512, -2.359])#origin
#     teachPoint(c,[0.,0.,30.,0.,0.,0.],TF=8,UF=8)
#     pos=getRobotP(c)
#     teachPoint(c,[0.,50.,30.,0.,0.,0.],TF=8,UF=8)
#     pos=getRobotP(c)
#     teachPoint(c,[0.,0.,30.,0.,0.,0.],TF=8,UF=8)
#     pos=getRobotP(c)
#     teachPoint(c,[50.,0.,30.,0.,0.,0.],TF=8,UF=8)
#     pos=getRobotP(c)


## calculate UF

In [23]:
# Tco=euler2H(UF[0])
# # --Cal Tbe--
# changeUF(c,UF=0)
# changeTF(c,TF=0)
# pos=getRobotP(c)
# Tbe=euler2H(pos)

# # --ChangeTF(_TFidx)
# # --Get Camera TF--
# # Width, Height, Angle, Roll, Pitch, Yaw = GetTF(_TFidx)
# Tool=getTF(c,TF=7)
# print(Tool)
# # Tx=Width*COS(Angle)
# Tx=Tool[0]*math.cos(Tool[2])
# # Ty=Width*SIN(Angle)
# Ty=Tool[0]*math.sin(Tool[2])
# # Tec=PO2H(Tx,Ty,Height,Yaw,Pitch,Roll)
# Tec=euler2H([Tx,Ty,Tool[1],Tool[3],Tool[4],Tool[5]])

# # --Cal UF--
# axisX=np.array([100,0,0,1])
# axisY=np.array([0,100,0,1])
# Tbc=Tbe.dot(Tec)
# Tbo=Tbc.dot(Tco)
# UF_O=[Tbo[0][3],Tbo[1][3],Tbo[2][3]]
# # UF_X=matrix.mul(Tbo,axisX)
# UF_X=Tbo.dot(axisX)
# # UF_Y=matrix.mul(Tbo,axisY)
# UF_Y=Tbo.dot(axisY)

# # JRC = {0,0,0,0,0,1,0,1}
# # SetGlobalPoint(1,"GL_1",UF_O[1], UF_O[2],UF_O[3],0,0,0,0,0,0,0,0,JRC)
# # SetGlobalPoint(2,"GL_2",UF_X[1][1], UF_X[2][1],UF_X[3][1],0,0,0,0,0,0,0,0,JRC)
# # SetGlobalPoint(3,"GL_3",UF_Y[1][1], UF_Y[2][1],UF_Y[3][1],0,0,0,0,0,0,0,0,JRC)
# # SetUF(_UFidx,1,2,3,1)

# # ChangeUF(_UFidx)
# # ChangeTF(_TFidx)

[101.481, 42.304, -19.246, -0.461, 1.994, 87.835]


array([ 557.28949903, -241.4230152 ,  145.79091209,    1.        ])

## setUF

In [29]:
# # setUF(c,o,x,y,TF=0)
# TF=0
# c.open()
# #o
# pos=float2int(UF_O)
# for i in range(3):
#     c.write_multiple_registers((0x1210+2*i), intL2DRA(pos[i]))
# c.write_multiple_registers(0x121C, int2DRA(TF))#TF
# c.write_multiple_registers(0x121D, int2DRA(0))#UF

# #x
# pos=float2int(UF_X)
# for i in range(3):
#     c.write_multiple_registers((0x1220+2*i), intL2DRA(pos[i]))
# c.write_multiple_registers(0x122C, int2DRA(TF))#TF
# c.write_multiple_registers(0x122D, int2DRA(0))#UF
# #y
# pos=float2int(UF_Y)
# for i in range(3):
#     c.write_multiple_registers((0x1230+2*i), intL2DRA(pos[i]))
# c.write_multiple_registers(0x123C, int2DRA(TF))#TF
# c.write_multiple_registers(0x123D, int2DRA(0))#UF

# c.write_multiple_registers(0x121F, int2DRA(8))#UF
# c.write_multiple_registers(0x1001, int2DRA(5))#tell dra to run
# time.sleep(1)

# c.write_multiple_registers(0x1001, int2DRA(0))
# c.close   

<bound method ModbusClient.close of <pyModbusTCP.client.ModbusClient object at 0x0600EE80>>

In [45]:
# c.open()
# c.write_multiple_registers(0x1001, int2DRA(9))
# time.sleep(1)
# c.write_multiple_registers(0x1001, int2DRA(0))
# c.close 
graspDemo(c)

<bound method ModbusClient.close of <pyModbusTCP.client.ModbusClient object at 0x0600EE80>>