In [ ]:
# [[919.5861236    0.         641.38367948]
#  [  0.         924.60020836 352.86391377]
#  [  0.           0.           1.        ]]
# [[ 0.14943493 -0.23997318  0.00054742 -0.00434003 -0.28933569]]
# error: 0.32133489939044263
# distortion: [[ 0.14943493 -0.23997318  0.00054742 -0.00434003 -0.28933569]]
# 目錄存在。
# write charuco pose finish with  22 imgs
# Camera Tool Size:
#  Width(mm):  104.34001611149618  Height(mm):  41.11848553464706  Angle(degree):  -19.616746159823723
# Camera Tool Orientation:
#  Rx:  0.0017863385088532323  Ry:  0.2032609565288365  Rz:  87.88670891951666

In [9]:
from camCalibration import *

cam1=Charuco()
#cam1.readCameraConfig("./pic_highres/data")
# cam1.Calibration(imgPath="./8_3_high",show=False)
# cam1.HandEyeCalibration_HandInEye()#new 按照數字讀圖
# cam1=Charuco()
#cam1.readCameraConfig("./pic_highres/data")
cam1.Calibration(imgPath="./8_3_3_high",show=False)
cam1.HandEyeCalibration_EyeInHand()#new 按照數字讀圖



[[917.31791866   0.         640.58334633]
 [  0.         921.29657002 351.55788766]
 [  0.           0.           1.        ]]
[[ 9.31302546e-02  2.88921840e-01  5.60167537e-04 -5.47268159e-03
  -1.63561171e+00]]
error: 0.3216717748710815
distortion: [[ 9.31302546e-02  2.88921840e-01  5.60167537e-04 -5.47268159e-03
  -1.63561171e+00]]
目錄存在。
write charuco pose finish with  25 imgs
Camera Tool Size:
 Width(mm):  102.90229300123517  Height(mm):  37.05430555438235  Angle(degree):  -17.037969188668907
Camera Tool Orientation:
 Rx:  -0.03684360466233889  Ry:  -0.5139679622380616  Rz:  87.99906944235656


In [3]:
from camCalibration import *
cam1=Charuco()
#cam1.readCameraConfig("./pic_highres/data")
cam1.Calibration(imgPath="./8_3_2_high",show=False)
cam1.HandEyeCalibration_EyeInHand()#new 按照數字讀圖
cam1=Charuco()
#cam1.readCameraConfig("./pic_highres/data")
cam1.Calibration(imgPath="./8_3_2_high2",show=False)
cam1.HandEyeCalibration_EyeInHand()#new 按照數字讀圖

[[921.45383042   0.         637.64599033]
 [  0.         924.49414357 348.71998379]
 [  0.           0.           1.        ]]
[[ 1.20551352e-01  9.72967150e-03 -5.04358549e-04 -6.95081299e-03
  -7.07844673e-01]]
error: 0.32280209231935963
distortion: [[ 1.20551352e-01  9.72967150e-03 -5.04358549e-04 -6.95081299e-03
  -7.07844673e-01]]
目錄存在。
write charuco pose finish with  22 imgs
Camera Tool Size:
 Width(mm):  104.1702683932872  Height(mm):  34.57964793127251  Angle(degree):  -19.584002370867786
Camera Tool Orientation:
 Rx:  0.4228246014861713  Ry:  -0.2928115405784626  Rz:  88.37027613792884
[[921.66608724   0.         638.74617801]
 [  0.         924.97612261 352.76633002]
 [  0.           0.           1.        ]]
[[ 1.24481242e-01 -1.02747825e-02  5.74798944e-04 -6.51290512e-03
  -7.09304751e-01]]
error: 0.31596269584123504
distortion: [[ 1.24481242e-01 -1.02747825e-02  5.74798944e-04 -6.51290512e-03
  -7.09304751e-01]]
目錄存在。
write charuco pose finish with  22 imgs
Camera Tool Si

In [7]:
from camCalibration import *
cam2=Charuco()
# cam2.readCameraConfig("./pic_highres/data")
# cam2.squaresY
cam2.Calibration(imgPath="./8_3_low",show=False)
cam2.HandEyeCalibration_EyeInHand()
cam4=Charuco()
# cam2.readCameraConfig("./pic_highres/data")
# cam2.squaresY
cam4.Calibration(imgPath="./8_3_low2",show=False)
cam4.HandEyeCalibration_EyeInHand()

[[611.29633273   0.         320.28558664]
 [  0.         613.94552229 234.40940698]
 [  0.           0.           1.        ]]
[[ 8.84100125e-02  3.27931698e-01  3.25481225e-04 -5.33713569e-03
  -1.76261118e+00]]
error: 0.20042274540945584
distortion: [[ 8.84100125e-02  3.27931698e-01  3.25481225e-04 -5.33713569e-03
  -1.76261118e+00]]
目錄存在。
write charuco pose finish with  22 imgs
Camera Tool Size:
 Width(mm):  106.17156357421382  Height(mm):  36.85710647293746  Angle(degree):  -19.063449186544947
Camera Tool Orientation:
 Rx:  -0.08682163144496063  Ry:  0.07005692450786968  Rz:  88.13308493127882
[[612.76429695   0.         321.0474957 ]
 [  0.         615.24187295 235.59064389]
 [  0.           0.           1.        ]]
[[ 8.29202648e-02  3.72549342e-01  4.75518435e-04 -5.02401254e-03
  -1.85039028e+00]]
error: 0.21468018977057463
distortion: [[ 8.29202648e-02  3.72549342e-01  4.75518435e-04 -5.02401254e-03
  -1.85039028e+00]]
目錄存在。
write charuco pose finish with  18 imgs
Camera Tool

In [8]:
cam4=Charuco()
# cam2.readCameraConfig("./pic_highres/data")
# cam2.squaresY
cam4.Calibration(imgPath="./8_3_low2",show=False)
cam4.HandEyeCalibration_EyeInHand()

[[609.85183091   0.         321.22712177]
 [  0.         612.48042607 234.50888008]
 [  0.           0.           1.        ]]
[[ 8.05671005e-02  3.92328920e-01  2.43330555e-04 -4.89112636e-03
  -1.93538029e+00]]
error: 0.2072915277809871
distortion: [[ 8.05671005e-02  3.92328920e-01  2.43330555e-04 -4.89112636e-03
  -1.93538029e+00]]
目錄存在。
write charuco pose finish with  25 imgs
Camera Tool Size:
 Width(mm):  103.95249120210728  Height(mm):  36.1675436727929  Angle(degree):  -17.446912129179132
Camera Tool Orientation:
 Rx:  -0.11218809899833701  Ry:  -0.29064356311091244  Rz:  87.9933291032136


In [1]:
from camCalibration import *
cam2=Charuco()
# cam2.readCameraConfig("./pic_highres/data")
# cam2.squaresY
cam2.Calibration(imgPath="./8_3_high",show=False)
cam2.HandEyeCalibration_HandInEye()#old 按照glob讀圖順序
cam4=Charuco()
# cam2.readCameraConfig("./pic_highres/data")
# cam2.squaresY
cam4.Calibration(imgPath="./8_3_high2",show=False)
cam4.HandEyeCalibration_HandInEye()#old 按照glob讀圖順序

[[918.59202535   0.         640.54031716]
 [  0.         923.48282643 351.7056176 ]
 [  0.           0.           1.        ]]
[[ 1.42872707e-01 -1.82161926e-01  3.92874072e-04 -4.68419856e-03
  -4.28553845e-01]]
error: 0.32691430943860716
目錄存在。
write charuco pose finish with  22 imgs
Camera Tool Size:
 Width(mm):  19.426704590556717  Height(mm):  224.25886544247751  Angle(degree):  -90.0
Camera Tool Orientation:
 Rx:  10.515607818338209  Ry:  5.150692527764665  Rz:  -71.22552101394811
[[919.58612434   0.         641.38368059]
 [  0.         924.60020915 352.86391314]
 [  0.           0.           1.        ]]
[[ 0.14943493 -0.23997318  0.00054742 -0.00434003 -0.28933568]]
error: 0.32133489939044263
目錄存在。
write charuco pose finish with  22 imgs
Camera Tool Size:
 Width(mm):  19.625569602615336  Height(mm):  224.0010952553457  Angle(degree):  -90.0
Camera Tool Orientation:
 Rx:  9.297969484740927  Ry:  1.8748052235224018  Rz:  -71.07495064324132


In [23]:
# a=readtxt('pic3/data/robot.txt')
a=readtxt('pic_highres/data/CameraPose.txt')
b=readtxt('pic_highres/data/Robot.txt')
len(b)


22

In [19]:
print(a.shape,b.shape)

AttributeError: 'int' object has no attribute 'shape'

In [6]:
import math
import numpy as np
import cv2
    
a=np.array([[1,2,3],[4,5,6]])
print(a)
print(a[1,2])
#HandEyeCalibration_HandInEye()

[[1 2 3]
 [4 5 6]]
6


In [8]:
import glob
import cv2
imgPath="./8_3_high2"
images = glob.glob(imgPath+'/*_color.jpg')
print(images)
j=0
for i in range(len(images)):
    print(images[i])
    print(imgPath+'\\00'+str(i+1)+'_color.jpg')
    
    img=cv2.imread(images[i])
    cv2.imshow(images[j], img)
    cv2.waitKey(0)
    img=cv2.imread(imgPath+'/00'+str(i+1)+'_color.jpg')
    cv2.imshow(imgPath+'/'+str(i+1)+'_color.jpg')
    cv2.waitKey(0)
    cv2.destroyAllWindows()
    j+=1

['./8_3_high2\\001_color.jpg', './8_3_high2\\002_color.jpg', './8_3_high2\\003_color.jpg', './8_3_high2\\004_color.jpg', './8_3_high2\\005_color.jpg', './8_3_high2\\006_color.jpg', './8_3_high2\\007_color.jpg', './8_3_high2\\008_color.jpg', './8_3_high2\\009_color.jpg', './8_3_high2\\010_color.jpg', './8_3_high2\\011_color.jpg', './8_3_high2\\012_color.jpg', './8_3_high2\\013_color.jpg', './8_3_high2\\014_color.jpg', './8_3_high2\\015_color.jpg', './8_3_high2\\016_color.jpg', './8_3_high2\\017_color.jpg', './8_3_high2\\018_color.jpg', './8_3_high2\\019_color.jpg', './8_3_high2\\020_color.jpg', './8_3_high2\\021_color.jpg', './8_3_high2\\022_color.jpg']
./8_3_high2\001_color.jpg
./8_3_high2\001_color.jpg


error: OpenCV(4.5.3) :-1: error: (-5:Bad argument) in function 'imshow'
> Overload resolution failed:
>  - imshow() missing required argument 'mat' (pos 2)
>  - imshow() missing required argument 'mat' (pos 2)
>  - imshow() missing required argument 'mat' (pos 2)


In [ ]:
#tool frame 7