In [2]:
import cv2
import pyrealsense2 as rs
import numpy as np
from camCalibration import *
from Modbus_DW import *
from camera import *
from demo import demo

In [2]:
c=connectRobot(SERVER_HOST = "192.168.1.1")
pos = getRobotP(c)
#save
data = {}
data['robotEnd'] = pos
with open('robotEnd.yaml', 'w') as f:
    yaml.dump(data, f)

with open('robotEnd.yaml'  , 'r') as f:
    data2 = yaml.load(f, Loader=yaml.Loader)
data2['robotEnd']

connect success
DRA is runing now
read try: 0
read try: 1


[171.672, 394.785, 763.431, -178.448, 1.785, -8.966]

## make calibration data

In [4]:
c=connectRobot(SERVER_HOST = "192.168.1.1")
pos1=[294.016, 69.194, 726.437, 178.57, 0.17, -3.244]
# teachPoint(c,pos1)
# print(pos1)
pos=getRobotP(c)
print(pos)
# pos1=[354.016, 69.194, 726.437, 178.57, 0.17, -3.244]



TypeError: 'str' object is not callable

In [4]:
makeCamset(c,path="picture/Demo",pixel="high",p0=pos,align=True)   #p0=pos
# # teachPoint(c,pos)

wait for move 0
wait for move 1
wait for move 2
wait for move 3
wait for move 4
read try: 0
[294.015, 69.193, 726.436, 178.569, 0.169, -3.243]
目錄存在。
內有: 0 對圖片
start camera:
目錄不存在。建一個目錄...
wait for move 0
wait for move 1
wait for move 2
wait for move 3
wait for move 4
read try: 0
[304.015, 69.192, 726.435, 178.569, 0.17, -3.243]
目錄存在。
內有: 1 對圖片
start camera:
目錄存在。
wait for move 0
wait for move 1
wait for move 2
wait for move 3
wait for move 4
read try: 0
[294.014, 49.194, 726.435, 178.57, 0.17, 11.756]
目錄存在。
內有: 2 對圖片
start camera:
目錄存在。
wait for move 0
wait for move 1
wait for move 2
wait for move 3
wait for move 4
read try: 0
[294.015, 89.191, 726.435, 178.569, 0.169, -18.244]
目錄存在。
內有: 3 對圖片
start camera:
目錄存在。
wait for move 0
wait for move 1
wait for move 2
wait for move 3
wait for move 4
read try: 0
[294.014, 79.194, 726.436, 178.57, 0.17, -3.243]
目錄存在。
內有: 4 對圖片
start camera:
目錄存在。
wait for move 0
wait for move 1
wait for move 2
wait for move 3
wait for move 4
read try: 0
[294.015

In [3]:
path="./picture/11_29_2"
with open(path+"/data/HandEye.yaml", 'r') as f:
    data = yaml.load(f, Loader=yaml.Loader)
print(data)

{'CameraTool_Angle': 30.877102701429383, 'CameraTool_Height': 159.3441456764351, 'CameraTool_Rx': -0.4010061372870978, 'CameraTool_Ry': 0.904995180312444, 'CameraTool_Rz': 87.62910560491574, 'CameraTool_Width': 103.10175044208098}


## run Hand Eye calibration

In [6]:
cam1=Charuco()
cam1.Calibration(imgPath="./picture/Demo",show=False)
# cam1.Calibration(imgPath="./picture/12_17",show=True)
cam1.HandEyeCalibration_EyeInHand()#new 按照數字讀圖

c=connectRobot(SERVER_HOST = "192.168.1.1")
RWTool(c,path="./picture/Demo")

[[964.14536251   0.         617.4905916 ]
 [  0.         963.96259412 369.68404351]
 [  0.           0.           1.        ]]
[[ 0.15437546 -0.06680524  0.00748756 -0.01206885 -0.77194777]]
error: 0.3063435267539898
distortion: [[ 0.15437546 -0.06680524  0.00748756 -0.01206885 -0.77194777]]
目錄存在。
write charuco pose finish with  25 imgs
Rotation matrix tool frame
 [[ 0.04513774 -0.99813759  0.04103583]
 [ 0.99879771  0.04587775  0.01727354]
 [-0.019124    0.04020681  0.99900835]]
Trans matrix tool frame
 [[ 81.41382969]
 [ 45.50357665]
 [156.98592162]]
Camera Tool Size:
 Width(mm):  93.26728876118096  Height(mm):  156.98592161733077  Angle(degree):  29.201568631249955
Camera Tool Orientation:
 Rx:  2.3047232292507926  Ry:  1.0957911164791276  Rz:  87.41244554926787
connect success
DRA is runing now
[93.26728876118096, 156.98592161733077, 29.201568631249955, 2.3047232292507926, 1.0957911164791276, 87.41244554926787]


In [7]:
path="./picture/Demo"
with open(path+"/data/HandEye.yaml", 'r') as f:
    data = yaml.load(f, Loader=yaml.Loader)
print(data)

{'CameraTool_Angle': 29.201568631249955, 'CameraTool_Height': 156.98592161733077, 'CameraTool_Rx': 2.3047232292507926, 'CameraTool_Ry': 1.0957911164791276, 'CameraTool_Rz': 87.41244554926787, 'CameraTool_Width': 93.26728876118096}


## demo UF

In [2]:
pipeline=startCamera()
# run=demo("./picture/8_9")
run=demo("./picture/11_29_2")
c=connectRobot(SERVER_HOST = "192.168.1.1")

try:
    while True:
        Cam,colorImg,depthImg=CameraStream(pipeline)
        if(Cam==0):#esc
            break
        elif(Cam==1):
            continue
        elif(Cam==3):#press 1
            #print("1")
            a,UF=run.getSinglePose(colorImg)
            print("UF:",UF)
            o,x,y=run.calUF(c)
            print("UF origin, x, y =",o,x,y)
            setUF(c,o,x,y)
            #setUF(c,UF[0],UF[1],UF[2],TF=7)
#             pointBoardPose(c)
#             teachPoint(c,[437.195, -50.004, 570.37, 177.131, -1.512, -2.359])#origin
            graspDemo(c)
        else:
#             print("123")
            continue
        
finally:

    # Stop streaming
    pipeline.stop()
    cv2.destroyAllWindows()
    #closeRobot(c)

hello
{'ARUCO_size': 6, 'dist': array([[ 0.16269981, -0.21051283,  0.00716262, -0.00676228, -0.26399864]]), 'iMtx': array([[947.35677163,   0.        , 631.87979122],
       [  0.        , 949.73990136, 367.38558855],
       [  0.        ,   0.        ,   1.        ]]), 'markerL': 0.015, 'squareL': 0.02, 'x': 9, 'y': 12}
connect success
DRA is runing now
UF: [19.545109794176312, -97.8309533098665, 625.4827353413757, -179.83718701900858, -1.0809675415579985, 82.71429378886296]
read try: 0
UF origin, x, y = [410.42806713498413, 15.249178075140335, -26.556666670385084] [310.48366872  12.83335597 -24.25861779   1.        ] [412.87132008 -84.71408621 -25.38350516   1.        ]


In [6]:
Tool=[103.101, 159.344, 30.877, -0.401, 0.904, 87.629]
deg2reg=math.pi/180
print(Tool[0]*math.sin(Tool[2]*deg2reg))

math.sin(Tool[2])

52.91109929311299


-0.5132149761245706

In [ ]:
# UF.shape
#changeUF(c,UF=0)  #board UF=8
# changeTF(c,TF=0) #camera tool frame = 7,筷子=8


In [2]:
# def pointBoardPose(c):
# #     changeUF(c,UF=8)  #board UF=8
# #     changeTF(c,TF=7)
# #     teachPoint(c,[437.195, -50.004, 570.37, 177.131, -1.512, -2.359])#origin
#     teachPoint(c,[0.,0.,30.,0.,0.,0.],TF=8,UF=8)
#     pos=getRobotP(c)
#     teachPoint(c,[0.,50.,30.,0.,0.,0.],TF=8,UF=8)
#     pos=getRobotP(c)
#     teachPoint(c,[0.,0.,30.,0.,0.,0.],TF=8,UF=8)
#     pos=getRobotP(c)
#     teachPoint(c,[50.,0.,30.,0.,0.,0.],TF=8,UF=8)
#     pos=getRobotP(c)


## calculate UF

In [23]:
# Tco=euler2H(UF[0])
# # --Cal Tbe--
# changeUF(c,UF=0)
# changeTF(c,TF=0)
# pos=getRobotP(c)
# Tbe=euler2H(pos)

# # --ChangeTF(_TFidx)
# # --Get Camera TF--
# # Width, Height, Angle, Roll, Pitch, Yaw = GetTF(_TFidx)
# Tool=getTF(c,TF=7)
# print(Tool)
# # Tx=Width*COS(Angle)
# Tx=Tool[0]*math.cos(Tool[2])
# # Ty=Width*SIN(Angle)
# Ty=Tool[0]*math.sin(Tool[2])
# # Tec=PO2H(Tx,Ty,Height,Yaw,Pitch,Roll)
# Tec=euler2H([Tx,Ty,Tool[1],Tool[3],Tool[4],Tool[5]])

# # --Cal UF--
# axisX=np.array([100,0,0,1])
# axisY=np.array([0,100,0,1])
# Tbc=Tbe.dot(Tec)
# Tbo=Tbc.dot(Tco)
# UF_O=[Tbo[0][3],Tbo[1][3],Tbo[2][3]]
# # UF_X=matrix.mul(Tbo,axisX)
# UF_X=Tbo.dot(axisX)
# # UF_Y=matrix.mul(Tbo,axisY)
# UF_Y=Tbo.dot(axisY)

# # JRC = {0,0,0,0,0,1,0,1}
# # SetGlobalPoint(1,"GL_1",UF_O[1], UF_O[2],UF_O[3],0,0,0,0,0,0,0,0,JRC)
# # SetGlobalPoint(2,"GL_2",UF_X[1][1], UF_X[2][1],UF_X[3][1],0,0,0,0,0,0,0,0,JRC)
# # SetGlobalPoint(3,"GL_3",UF_Y[1][1], UF_Y[2][1],UF_Y[3][1],0,0,0,0,0,0,0,0,JRC)
# # SetUF(_UFidx,1,2,3,1)

# # ChangeUF(_UFidx)
# # ChangeTF(_TFidx)

[101.481, 42.304, -19.246, -0.461, 1.994, 87.835]


array([ 557.28949903, -241.4230152 ,  145.79091209,    1.        ])

## setUF

In [29]:
# # setUF(c,o,x,y,TF=0)
# TF=0
# c.open()
# #o
# pos=float2int(UF_O)
# for i in range(3):
#     c.write_multiple_registers((0x1210+2*i), intL2DRA(pos[i]))
# c.write_multiple_registers(0x121C, int2DRA(TF))#TF
# c.write_multiple_registers(0x121D, int2DRA(0))#UF

# #x
# pos=float2int(UF_X)
# for i in range(3):
#     c.write_multiple_registers((0x1220+2*i), intL2DRA(pos[i]))
# c.write_multiple_registers(0x122C, int2DRA(TF))#TF
# c.write_multiple_registers(0x122D, int2DRA(0))#UF
# #y
# pos=float2int(UF_Y)
# for i in range(3):
#     c.write_multiple_registers((0x1230+2*i), intL2DRA(pos[i]))
# c.write_multiple_registers(0x123C, int2DRA(TF))#TF
# c.write_multiple_registers(0x123D, int2DRA(0))#UF

# c.write_multiple_registers(0x121F, int2DRA(8))#UF
# c.write_multiple_registers(0x1001, int2DRA(5))#tell dra to run
# time.sleep(1)

# c.write_multiple_registers(0x1001, int2DRA(0))
# c.close   

<bound method ModbusClient.close of <pyModbusTCP.client.ModbusClient object at 0x0600EE80>>

In [13]:
# teachPoint(c,[171.672, 394.786, 583.037, -178.449, 1.786, -8.965])
# c.open()
# c.write_multiple_registers(0x1001, int2DRA(9))
# time.sleep(2)
# c.write_multiple_registers(0x1001, int2DRA(0))
# c.close 

graspDemo(c)

wait for move 0
wait for move 1
wait for move 2
wait for move 3
wait for move 4
wait for move 0
wait for move 1
wait for move 2
wait for move 3
wait for move 4


In [4]:
pos=getRobotP(c)
Tbe=euler2H(pos)

# --ChangeTF(_TFidx)
# --Get Camera TF--
# Width, Height, Angle, Roll, Pitch, Yaw = GetTF(_TFidx)
Tool=getTF(c,TF=2)

# Tx=Width*COS(Angle)
deg2reg=math.pi/180
Tx=Tool[0]*math.cos(Tool[2]*deg2reg)
# Ty=Width*SIN(Angle)
Ty=Tool[0]*math.sin(Tool[2]*deg2reg)
# Tec=PO2H(Tx,Ty,Height,Yaw,Pitch,Roll)
Tec=euler2H([Tx,Ty,Tool[1],Tool[3],Tool[4],Tool[5]])

# --Cal UF--
axisX=np.array([100,0,0,1])
axisY=np.array([0,100,0,1])
Tbc=Tbe.dot(Tec)

read try: 0


In [5]:
Tbc

array([[-1.15195111e-01, -9.92714533e-01, -3.53262419e-02,
         2.46518224e+02],
       [-9.93263570e-01,  1.14663651e-01,  1.67250801e-02,
         3.33797647e+02],
       [-1.25525942e-02,  3.70149166e-02, -9.99235872e-01,
         6.00033441e+02],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.00000000e+00]])

In [6]:
import yaml
path='../python_code/realsense/'
data={}
data['matrix']=Tbc
with open(path+'right_init_high.yaml', 'w') as f:
        yaml.dump(data, f)